spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID_GOOGLE}
            clientSecret: ${CLIENT_SECRET_GOOGLE}
            scope:
              - email
              - profile
